version: '4'

services:
  app:
    build: ./docker/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes: 
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    container_name: php
    networks:
      - app-network
    depends_on:
      - db

  app-nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    tty: true
    ports: 
      - "8181:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/config/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app
      - db

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: url
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
